// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID        int64              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Corporation struct {
	ID           int64              `json:"id"`
	EntityID     int64              `json:"entity_id"`
	LegalName    string             `json:"legal_name"`
	Jurisdiction pgtype.Text        `json:"jurisdiction"`
	Ein          []byte             `json:"ein"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Entity struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	FundamentalTypeID int64              `json:"fundamental_type_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt        *time.Time         `json:"archived_at"`
	OwnerID           pgtype.Int8        `json:"owner_id"`
}

type LegalEntity struct {
	EntityID int64 `json:"entity_id"`
}

type NaturalPerson struct {
	ID         int64              `json:"id"`
	EntityID   int64              `json:"entity_id"`
	GivenName  pgtype.Text        `json:"given_name"`
	FamilyName pgtype.Text        `json:"family_name"`
	Ssn        []byte             `json:"ssn"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ServiceAccount struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	EntityID  int64              `json:"entity_id"`
	OwnerID   int64              `json:"owner_id"`
	SubjectID int64              `json:"subject_id"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TagTemplate struct {
	ID        int64              `json:"id"`
	Scope     pgtype.Int8        `json:"scope"`
	Purpose   string             `json:"purpose"`
	Value     string             `json:"value"`
	Label     string             `json:"label"`
	Color     pgtype.Text        `json:"color"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Type struct {
	ID           int64              `json:"id"`
	Slug         string             `json:"slug"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	Concrete     bool               `json:"concrete"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeprecatedAt *time.Time         `json:"deprecated_at"`
}
