// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTagsBySubjectEntityID(ctx context.Context, arg CountTagsBySubjectEntityIDParams) (int64, error)
	// Optional filters use the (sqlc.narg('name')::type IS NULL OR col = sqlc.narg('name')::type)
	// pattern so the generated params struct has readable, nullable field names (pgtype.Text,
	// pgtype.Int8, etc.) instead of positional Column1/Column2 names.
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteTag(ctx context.Context, entityID int64) error
	GetTagByEntityID(ctx context.Context, entityID int64) (Tag, error)
	GetTagByEntityUUID(ctx context.Context, argUuid uuid.UUID) (GetTagByEntityUUIDRow, error)
	GetTagPurposePolicy(ctx context.Context, purpose string) (TagPurposePolicy, error)
	ListTagTemplates(ctx context.Context, arg ListTagTemplatesParams) ([]ListTagTemplatesRow, error)
	ListTagsBySubjectEntityID(ctx context.Context, arg ListTagsBySubjectEntityIDParams) ([]ListTagsBySubjectEntityIDRow, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]SearchTagsRow, error)
	UpdateTagColor(ctx context.Context, arg UpdateTagColorParams) (Tag, error)
	UpdateTagValue(ctx context.Context, arg UpdateTagValueParams) (Tag, error)
	UpsertTagPurposePolicy(ctx context.Context, arg UpsertTagPurposePolicyParams) (TagPurposePolicy, error)
	// UpsertTagTemplate inserts or updates a single app-scoped (non-null-scope)
	// tag_templates row, keyed by (scope, purpose, value). The ON CONFLICT
	// target repeats the "WHERE scope IS NOT NULL" predicate of the
	// tag_templates_scoped_purpose_value_idx partial unique index (see
	// 0204_tag_templates.sql) — Postgres requires an ON CONFLICT clause's
	// predicate to match a partial index's predicate exactly for it to be used
	// as the arbiter. This query is not usable for global (NULL-scope) rows,
	// which are deduped by a separate partial index instead.
	UpsertTagTemplate(ctx context.Context, arg UpsertTagTemplateParams) (UpsertTagTemplateRow, error)
}

var _ Querier = (*Queries)(nil)
