// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTagTemplates = `-- name: ListTagTemplates :many
SELECT tt.purpose, tt.value, tt.label, tt.color, tt.sort_order,
       tt.scope, e.uuid AS scope_uuid,
       COALESCE(tpp.one_of_domain, false) AS one_of_domain
FROM tag_templates tt
LEFT JOIN entities e ON e.id = tt.scope
LEFT JOIN tag_purpose_policies tpp ON tpp.purpose = tt.purpose
WHERE tt.purpose = $1
  AND (tt.scope IS NULL OR tt.scope = $2::bigint)
ORDER BY tt.scope NULLS FIRST, tt.sort_order ASC, tt.value ASC
`

type ListTagTemplatesParams struct {
	Purpose string      `json:"purpose"`
	Scope   pgtype.Int8 `json:"scope"`
}

type ListTagTemplatesRow struct {
	Purpose     string      `json:"purpose"`
	Value       string      `json:"value"`
	Label       string      `json:"label"`
	Color       pgtype.Text `json:"color"`
	SortOrder   int32       `json:"sort_order"`
	Scope       pgtype.Int8 `json:"scope"`
	ScopeUuid   pgtype.UUID `json:"scope_uuid"`
	OneOfDomain bool        `json:"one_of_domain"`
}

func (q *Queries) ListTagTemplates(ctx context.Context, arg ListTagTemplatesParams) ([]ListTagTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTagTemplates, arg.Purpose, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagTemplatesRow
	for rows.Next() {
		var i ListTagTemplatesRow
		if err := rows.Scan(
			&i.Purpose,
			&i.Value,
			&i.Label,
			&i.Color,
			&i.SortOrder,
			&i.Scope,
			&i.ScopeUuid,
			&i.OneOfDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTagTemplate = `-- name: UpsertTagTemplate :one
INSERT INTO tag_templates (scope, purpose, value, label, color, sort_order)
VALUES ($1::bigint, $2, $3, $4, $5, $6)
ON CONFLICT (scope, purpose, value) WHERE scope IS NOT NULL
DO UPDATE SET label = EXCLUDED.label, color = EXCLUDED.color,
              sort_order = EXCLUDED.sort_order, updated_at = now()
RETURNING id, scope, purpose, value, label, color, sort_order
`

type UpsertTagTemplateParams struct {
	Scope     pgtype.Int8 `json:"scope"`
	Purpose   string      `json:"purpose"`
	Value     string      `json:"value"`
	Label     string      `json:"label"`
	Color     pgtype.Text `json:"color"`
	SortOrder int32       `json:"sort_order"`
}

type UpsertTagTemplateRow struct {
	ID        int64       `json:"id"`
	Scope     pgtype.Int8 `json:"scope"`
	Purpose   string      `json:"purpose"`
	Value     string      `json:"value"`
	Label     string      `json:"label"`
	Color     pgtype.Text `json:"color"`
	SortOrder int32       `json:"sort_order"`
}

// UpsertTagTemplate inserts or updates a single app-scoped (non-null-scope)
// tag_templates row, keyed by (scope, purpose, value). The ON CONFLICT
// target repeats the "WHERE scope IS NOT NULL" predicate of the
// tag_templates_scoped_purpose_value_idx partial unique index (see
// 0204_tag_templates.sql) — Postgres requires an ON CONFLICT clause's
// predicate to match a partial index's predicate exactly for it to be used
// as the arbiter. This query is not usable for global (NULL-scope) rows,
// which are deduped by a separate partial index instead.
func (q *Queries) UpsertTagTemplate(ctx context.Context, arg UpsertTagTemplateParams) (UpsertTagTemplateRow, error) {
	row := q.db.QueryRow(ctx, upsertTagTemplate,
		arg.Scope,
		arg.Purpose,
		arg.Value,
		arg.Label,
		arg.Color,
		arg.SortOrder,
	)
	var i UpsertTagTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Purpose,
		&i.Value,
		&i.Label,
		&i.Color,
		&i.SortOrder,
	)
	return i, err
}
