// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_purpose_policies.sql

package db

import (
	"context"
)

const getTagPurposePolicy = `-- name: GetTagPurposePolicy :one
SELECT purpose, one_of_domain, created_at, updated_at
FROM tag_purpose_policies
WHERE purpose = $1
`

func (q *Queries) GetTagPurposePolicy(ctx context.Context, purpose string) (TagPurposePolicy, error) {
	row := q.db.QueryRow(ctx, getTagPurposePolicy, purpose)
	var i TagPurposePolicy
	err := row.Scan(
		&i.Purpose,
		&i.OneOfDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTagPurposePolicy = `-- name: UpsertTagPurposePolicy :one
INSERT INTO tag_purpose_policies (purpose, one_of_domain)
VALUES ($1, $2)
ON CONFLICT (purpose) DO UPDATE SET one_of_domain = EXCLUDED.one_of_domain, updated_at = now()
RETURNING purpose, one_of_domain, created_at, updated_at
`

type UpsertTagPurposePolicyParams struct {
	Purpose     string `json:"purpose"`
	OneOfDomain bool   `json:"one_of_domain"`
}

func (q *Queries) UpsertTagPurposePolicy(ctx context.Context, arg UpsertTagPurposePolicyParams) (TagPurposePolicy, error) {
	row := q.db.QueryRow(ctx, upsertTagPurposePolicy, arg.Purpose, arg.OneOfDomain)
	var i TagPurposePolicy
	err := row.Scan(
		&i.Purpose,
		&i.OneOfDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
