// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTagTemplates = `-- name: ListTagTemplates :many
SELECT tt.purpose, tt.value, tt.label, tt.color, tt.sort_order,
       tt.scope, e.uuid AS scope_uuid
FROM tag_templates tt
LEFT JOIN entities e ON e.id = tt.scope
WHERE tt.purpose = $1
  AND (tt.scope IS NULL OR tt.scope = $2::bigint)
ORDER BY tt.scope NULLS FIRST, tt.sort_order ASC, tt.value ASC
`

type ListTagTemplatesParams struct {
	Purpose string      `json:"purpose"`
	Scope   pgtype.Int8 `json:"scope"`
}

type ListTagTemplatesRow struct {
	Purpose   string      `json:"purpose"`
	Value     string      `json:"value"`
	Label     string      `json:"label"`
	Color     pgtype.Text `json:"color"`
	SortOrder int32       `json:"sort_order"`
	Scope     pgtype.Int8 `json:"scope"`
	ScopeUuid pgtype.UUID `json:"scope_uuid"`
}

func (q *Queries) ListTagTemplates(ctx context.Context, arg ListTagTemplatesParams) ([]ListTagTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTagTemplates, arg.Purpose, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagTemplatesRow
	for rows.Next() {
		var i ListTagTemplatesRow
		if err := rows.Scan(
			&i.Purpose,
			&i.Value,
			&i.Label,
			&i.Color,
			&i.SortOrder,
			&i.Scope,
			&i.ScopeUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
